In [1]:
# Make sure you run: pip install -r requirements.txt

# Part 1: Basic Structures

In [2]:
# Import PyTorch and check version.

import torch
print(torch.__version__)

/home/steve/repos/education/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.4.0+cu121


In [3]:
# Create a tensor

# Create a 1D tensor (vector)
tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor)

# Create a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2], [3, 4]])
print(tensor_2d)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2],
        [3, 4]])


In [8]:
# Basic Operations

# Element-wise addition
tensor_add = tensor + 2
print(tensor_add)

# Element-wise multiplication
tensor_mul = tensor * 2
print(tensor_mul)

# Matrix multiplication
matrix_mul = torch.matmul(tensor_2d, tensor_2d)
print(matrix_mul)

tensor([3, 4, 5, 6, 7])
tensor([ 2,  4,  6,  8, 10])
tensor([[ 7, 10],
        [15, 22]])


In [9]:
# Automatic Differentiation

# Create a tensor with requires_grad=True to track operations on it.
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 1

# Compute gradients.
y.backward()

# Print the gradient (dy/dx)
print(x.grad)

tensor(7.)


In [10]:
# Moving tensors to GPU.

if torch.cuda.is_available():
    tensor_gpu = tensor.to('cuda')
    print(tensor_gpu)
else:
    print("GPU not available.")

GPU not available.


# Part 2: Training a Model and Doing Inference

In [11]:
# Import

In [12]:
# Create dataset

In [13]:
# Define linear model

In [14]:
# Define loss function, optimizer

In [15]:
# Train the model

In [16]:
# Perform inference